# Generated by Django 5.2.7 on 2025-11-06 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0757_realmuserdefault_web_inbox_show_channel_folders_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="realmuserdefault",
            name="week_starts_on",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="week_starts_on",
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
